name: Ensure PR Has Labels

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled
jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the job if no labels are found
        if:  ${{ github.event.pull_request.labels[0] == null }} 
        run: exit 1
