name: Check PR Labels

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled
permissions:
  pull-requests: write
jobs:
  check_labels:
    runs-on: ubuntu-latest

    env:
      HAS_LABELS: ${{ github.event.pull_request.labels[0] != null }}

    steps:
      - name: Add a comment to the PR if no labels
        if: env.HAS_LABELS == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Your pull request does not have any labels. Please add at least one label to pass the checks.'
            })

      - name: Fail the job if no labels are found
        if: env.HAS_LABELS == 'false'
        run: exit 1
        shell: bash
